"""
ExportService — Markdown → HTML → PDF + DOCX pipeline.
Uses WeasyPrint for high-quality HTML→PDF conversion.
Uses python-docx for DOCX export.
"""
from __future__ import annotations

import asyncio
import base64
from pathlib import Path
from typing import Optional

from app.config.settings import settings
from app.errors.export import PDFExportException, DOCXExportException, MarkdownExportException


# HTML template for the report
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

  * {{ box-sizing: border-box; margin: 0; padding: 0; }}

  body {{
    font-family: 'Inter', -apple-system, sans-serif;
    font-size: 11pt;
    line-height: 1.7;
    color: #1a1a2e;
    background: white;
    padding: 20mm 25mm;
    max-width: 210mm;
    margin: 0 auto;
  }}

  h1 {{ font-size: 22pt; color: #0f0f23; margin-bottom: 8mm; border-bottom: 3px solid #6366f1; padding-bottom: 4mm; }}
  h2 {{ font-size: 15pt; color: #1e1b4b; margin-top: 10mm; margin-bottom: 4mm; border-left: 4px solid #6366f1; padding-left: 4mm; }}
  h3 {{ font-size: 12pt; color: #312e81; margin-top: 6mm; margin-bottom: 2mm; }}

  p {{ margin-bottom: 4mm; text-align: justify; }}

  ul, ol {{ margin-left: 6mm; margin-bottom: 4mm; }}
  li {{ margin-bottom: 1mm; }}

  blockquote {{
    border-left: 4px solid #c7d2fe;
    padding-left: 4mm;
    margin: 4mm 0;
    color: #4338ca;
    background: #eef2ff;
    border-radius: 0 4px 4px 0;
    padding: 3mm 4mm;
  }}

  code {{
    font-family: 'Courier New', monospace;
    background: #f5f3ff;
    padding: 1px 4px;
    border-radius: 3px;
    font-size: 9pt;
  }}

  table {{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 6mm;
    font-size: 10pt;
  }}
  th {{
    background: #6366f1;
    color: white;
    padding: 3mm 4mm;
    text-align: left;
    font-weight: 600;
  }}
  td {{
    padding: 2mm 4mm;
    border-bottom: 1px solid #e5e7eb;
  }}
  tr:nth-child(even) {{ background: #f9fafb; }}

  img.chart {{
    width: 100%;
    max-width: 160mm;
    display: block;
    margin: 6mm auto;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
  }}

  sup {{ color: #6366f1; font-size: 8pt; font-weight: 600; }}

  a {{ color: #4f46e5; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}

  .page-break {{ page-break-after: always; }}

  hr {{ border: none; border-top: 2px solid #e5e7eb; margin: 8mm 0; }}

  .footer {{
    margin-top: 10mm;
    padding-top: 4mm;
    border-top: 1px solid #e5e7eb;
    font-size: 9pt;
    color: #6b7280;
    text-align: center;
  }}
</style>
</head>
<body>
{content}
<div class="footer">Generated by Multi-Agent AI Research Platform</div>
</body>
</html>"""


class ExportService:
    """
    Handles the full Markdown → HTML → PDF + DOCX export pipeline.
    All exports are written to the outputs/ directory.
    """

    def __init__(self, outputs_path: str = None):
        self.outputs_path = Path(outputs_path or settings.OUTPUTS_PATH)

    async def export_all(
        self,
        markdown: str,
        chart_paths: list[str],
        job_id: str,
        formats: list[str] = None,
    ) -> dict:
        """
        Export report in all requested formats.
        Returns dict: {pdf, docx, markdown, html} → file paths
        """
        formats = formats or ["pdf", "docx", "markdown"]
        result = {}

        # 1. Save Markdown
        md_path = self.outputs_path / "markdown" / f"{job_id}.md"
        md_path.parent.mkdir(parents=True, exist_ok=True)
        md_path.write_text(markdown, encoding="utf-8")
        result["markdown"] = str(md_path)

        # 2. Convert Markdown → HTML
        html = await asyncio.get_event_loop().run_in_executor(
            None, self._markdown_to_html, markdown, chart_paths
        )

        html_path = self.outputs_path / "reports" / f"{job_id}.html"
        html_path.parent.mkdir(parents=True, exist_ok=True)
        html_path.write_text(html, encoding="utf-8")
        result["html"] = str(html_path)

        # 3. HTML → PDF
        if "pdf" in formats:
            pdf_path = self.outputs_path / "pdf" / f"{job_id}.pdf"
            pdf_path.parent.mkdir(parents=True, exist_ok=True)
            success = await asyncio.get_event_loop().run_in_executor(
                None, self._html_to_pdf, html, str(pdf_path)
            )
            if success:
                result["pdf"] = str(pdf_path)

        # 4. Markdown → DOCX
        if "docx" in formats:
            docx_path = self.outputs_path / "docx" / f"{job_id}.docx"
            docx_path.parent.mkdir(parents=True, exist_ok=True)
            success = await asyncio.get_event_loop().run_in_executor(
                None, self._markdown_to_docx, markdown, chart_paths, str(docx_path)
            )
            if success:
                result["docx"] = str(docx_path)

        return result

    # ─── Markdown → HTML ──────────────────────────────────────────────────────

    def _markdown_to_html(self, markdown: str, chart_paths: list[str]) -> str:
        """Convert Markdown to full HTML, embedding charts as base64 images."""
        import markdown as md_lib
        from markdown.extensions import tables, fenced_code

        # Convert citation references [1] to superscripts
        import re
        processed_md = re.sub(r"\[(\d+)\]", r"<sup>[\1]</sup>", markdown)

        # Parse markdown → HTML
        html_content = md_lib.markdown(
            processed_md,
            extensions=["tables", "fenced_code", "nl2br", "toc"],
        )

        # Embed charts as base64 images
        if chart_paths:
            chart_html = ""
            for path in chart_paths:
                p = Path(path)
                if p.exists():
                    with open(p, "rb") as f:
                        img_b64 = base64.b64encode(f.read()).decode()
                    chart_html += f'<img class="chart" src="data:image/png;base64,{img_b64}" alt="Chart" />\n'

            # Insert charts after the first h2 section
            html_content = html_content.replace(
                "</h2>", f"</h2>\n{chart_html}", 1
            ) if chart_html else html_content

        title = markdown.split("\n")[0].lstrip("#").strip()
        return _HTML_TEMPLATE.format(title=title, content=html_content)

    # ─── HTML → PDF ───────────────────────────────────────────────────────────

    def _html_to_pdf(self, html: str, output_path: str) -> bool:
        """Convert HTML to PDF using WeasyPrint with fallback to pdfkit."""
        try:
            from weasyprint import HTML, CSS
            from weasyprint.text.fonts import FontConfiguration

            font_config = FontConfiguration()
            HTML(string=html, base_url=".").write_pdf(
                output_path,
                font_config=font_config,
            )
            return True
        except Exception as weasy_err:
            # WeasyPrint failed (either import, missing library like libgobject, or runtime crash)
            # Try pdfkit as fallback
            try:
                import pdfkit
                pdfkit.from_string(html, output_path)
                return True
            except Exception as pdfkit_err:
                # Both failed — return False instead of raising to avoid crashing pipeline
                return False

    # ─── Markdown → DOCX ──────────────────────────────────────────────────────

    def _markdown_to_docx(
        self, markdown: str, chart_paths: list[str], output_path: str
    ) -> bool:
        """Convert Markdown to DOCX using python-docx."""
        try:
            import re
            from docx import Document
            from docx.shared import Inches, Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement

            doc = Document()

            # Set font
            style = doc.styles["Normal"]
            style.font.name = "Calibri"
            style.font.size = Pt(11)

            # Parse markdown lines
            lines = markdown.split("\n")
            chart_idx = 0

            for line in lines:
                if line.startswith("# "):
                    doc.add_heading(line[2:].strip(), level=0)
                elif line.startswith("## "):
                    doc.add_heading(line[3:].strip(), level=1)
                elif line.startswith("### "):
                    doc.add_heading(line[4:].strip(), level=2)
                elif line.startswith("---"):
                    doc.add_paragraph("─" * 50)
                elif line.strip() == "":
                    continue
                else:
                    # Strip citation references for DOCX
                    clean = re.sub(r"\[(\d+)\]", r"[\1]", line)
                    doc.add_paragraph(clean)

            # Add charts
            if chart_paths:
                doc.add_heading("Charts", level=1)
                for path in chart_paths:
                    p = Path(path)
                    if p.exists():
                        doc.add_picture(str(p), width=Inches(6))
                        doc.add_paragraph("")

            doc.save(output_path)
            return True

        except Exception as e:
            raise DOCXExportException(str(e))
